language: android
dist: trusty
os: linux

before_install:
  - yes | sdkmanager "platforms;android-29"

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    # - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  ./gradlew build connectedCheck